app_name: app1

server:
  listen:
    host: "0.0.0.0"
    port: 8081

log:
  level: info

database:
  name: mysql
  server: ${MYSQL_SERVER}
  port: ${MYSQL_PORT}
  user: ${MYSQL_USER}

prometheus:
  address: http://prometheus:9090
